pyblog/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.sugnup_views, name='signup'),
    url(r'^login/$', views.login_views, name="login"),
    url(r'^logout/$', views.logout_views, name="logout")
]

pyblog/articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'
urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_details, name="detail"),
]

pyblog/pyblog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.home),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pyblog/accounts/models.py
from django.db import models

# Create your models here.

pyblog/articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default="default.png", blank=True)
    author = models.ForeignKey(
        User, default=None, on_delete=models.SET_NULL,  null=True)

    def __str__(self):
        return self.title

    def snippet(self):
        if(len(self.body) > 50):
            to_display = self.body[:50] + "..."
            return to_display
        else:
            to_display = self.body[:50]
            return to_display

pyblog/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

pyblog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def sugnup_views(request):
    if(request.method == 'POST'):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {
        'form': form
    })


def login_views(request):
    if(request.method == 'POST'):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if('next' in request.POST):
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {
        'form': form
    })


def logout_views(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

pyblog/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.


def article_list(request):
    articles = Article.objects.all().order_by("date")
    return render(request, "articles/article_list.html", {
        "articles": articles
    })


def article_details(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_details.html', {
        'article': article
    })


@login_required(login_url="/accounts/login/")
def article_create(request):
    if(request.method == 'POST'):
        form = forms.CreateArticle(request.POST, request.FILES)
        if(form.is_valid()):
            form.save()
            return redirect('articles:list')
        pass
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {
        'form': form
    })

pyblog/pyblog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def about(request):
    # return HttpResponse("About Page")
    return render(request, "aboutpage.html")


def home(request):
    # return HttpResponse("home Page")
    return render(request, "homepage.html")

pyblog/accounts/templates/accounts/login.html
{% extends 'base.html' %} {% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %} {{ form }} {% if request.GET.next %}
  <input type="hidden" name="next" value="{{ request.GET.next }}" />
  {% endif %}
  <input type="submit" value="Login" />
</form>
{% endblock %}

pyblog/accounts/templates/accounts/signup.html
{% extends 'base.html' %} {% block content %}
<h1>Sign up page</h1>
<form class="site-form" action="/accounts/signup/" method="post">
  {% csrf_token %} {{ form }}
  <input type="submit" value="Sign Up" />
</form>
{% endblock %}

pyblog/articles/templates/articles/article_create.html
{% extends 'base.html' %} {% block content %}
<div class="create-article">
  <h2>Create an awesome Article here...</h2>
  <form
    class="site-form"
    action="{% url 'articles:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %} {{ form }}
    <input type="submit" value="Create" />
  </form>
</div>

{% endblock %}

pyblog/articles/templates/articles/article_details.html
{% extends 'base.html' %} {% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{ article.thumb.url }}" alt="" />
    <h2>{{ article.title }}</h2>
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
  </div>
</div>
{% endblock %}

pyblog/articles/templates/articles/article_list.html
{% extends 'base.html' %} {% block content %}
<h1>Article List</h1>
<div class="articles">
  {% for article in articles %}
  <div class="article">
    <h2>
      <a href="{% url 'articles:detail' slug=article.slug %}"
        >{{ article.title }}</a
      >
    </h2>
    <p>{{ article.snippet }}</p>
    <p>{{ article.date }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

pyblog/templates/aboutpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>About US</h1>
    <p>I think i am love loving python more than JavaScript....</p>
</body>
</html>

pyblog/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>Articles</title>
  </head>
  <body>
    <div class="wrapper">
      <h1>
        <a href="{% url 'articles:list' %}"
          ><img src="{% static 'white.png' %}" alt="logo"
        /></a>
      </h1>
      <nav>
        <ul>
          <li>
            <form
              class="logout-link"
              action="{% url 'accounts:logout' %}"
              method="post"
            >
              {% csrf_token %}
              <input type="submit" value="Logout" />
            </form>
          </li>
        </ul>
      </nav>
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

pyblog/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is the home page</h1>
    <p>Welcome to the blog home page</p>
</body>
</html>